version: '3.4'
services:
  db:
    image: davimarques/mysql-brasilprev
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Brasil1000@
      MYSQL_USER: admin
      MYSQL_PASSWORD: Brasil1000@
      MYSQL_DATABASE: brasilprev
    ports:
      - "3309:3306"
    networks:
      - davimarques-network
  brasilprev:
    image: davimarques/brasilprev
    restart: always
    build: ./DesafioBrasil
    working_dir: /DesafioBrasil
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./DesafioBrasil:/DesafioBrasil
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - davimarques-network
networks:
  davimarques-network:
    driver: bridge